os:
  - linux
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2

install: true
    #- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    #- mvn clean install #-Dgpg.skip=true
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false